### ISSUE TITLE
ERROR ITMS-90535: "Unexpected CFBundleExecutable Key

### ISSUE THREAD

**Issue by JanC** [OfficeDev/ui-fabric-ios#10]
Hi,
I integrated ui-fabric-ios using Carthage `github "OfficeDev/ui-fabric-ios"` and everything works fine. When I submit my app to TestFlight, I get the error message

```
ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/AeroNavMap.app/Frameworks/OfficeUIFabric.framework/OfficeUIFabricResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue." 
```
I checked the contents of the `OfficeUIFabric.framework` and it does contain the executable

<img width="349" alt="Screenshot 2019-06-22 at 16 08 05" src="https://user-images.githubusercontent.com/707703/59964942-005eca80-9508-11e9-8844-1c4cec4657e1.png">

All my other 3rd party dependencies work fine. Any idea what could cause this issue?

**Comment by JanC** [comment]
I tried integrating `ui-fabric-ios` using Cocoapods and that works fine. It must be something with the xcode configuration.

While I know that the documentation does not specify Carthage for installation, it would be nice to have it working

**Comment by vladfilyakov** [comment]
Hi Jan

Thank you for reporting this issue. We didn't test consumption of Fabric via Carthage, but will do it now. My feeling is that we need to remove CFBundleExecutable key from Info.plist used for OfficeUIFabricResources target (just like the error message suggests). We will let you know about the results of our research.

Thanks,
Vlad

**Comment by vladfilyakov** [comment]
Jan, can you please try the following change locally and see if it fixes the issue?

https://github.com/OfficeDev/ui-fabric-ios/commit/522bd9d27a3bdb5e84b4513510a7624592814ee1

Thanks,
Vlad

**Comment by JanC** [comment]
Hi, yes that worked.
Thanks!

I've updated my initial PR to simply add the Carthage docs https://github.com/OfficeDev/ui-fabric-ios/pull/11

**Comment by vladfilyakov** [comment]
Hi Jan

Thank you for confirming. We will have an update with this change soon. I also approved and merged your PR.

Thanks,
Vlad
