### ISSUE TITLE
[Question] MSPopupMenuItem always shows checkmark on press

### ISSUE THREAD

**Issue by SpencerLynn** [OfficeDev/ui-fabric-ios#14]
Hi!

I have a question about how `MSPopupMenuItem`/`MSPopupMenuItemCell` works. I'm looking to present a list of options in a `MSPopupMenuController`, where clicking on each item causes some other UX to present itself (further screens in a navigation controller, etc).

So touching on the items in the list doesn't need to ever show a checkmark. However, it seems baked in by default. After pressing, it sets the item to "selected" and sets the accessType to checkmark.

I don't see any to override this behavior without completely bailing on `MSPopupMenuController` and using the drawer and building the list myself. Would this project be open to expanding the functionality to support this "list of actions" rather than a "list of items to choose between".

I could be using `MSPopupMenuController` incorrectly, so please let me know if this incorrect or confusing.

Thanks!

**Comment by vladfilyakov** [comment]
Hi Spencer

Check mark that you can briefly see when selecting an item (popup menu closes at the same time) is just an indication of selection. If you do not store this value AND assign it back when you show a popup menu again, then it does not become "selected state" and is not persisted.

When you pick one action from several presented actions you still have "list of items to choose between" - it's just that on each popup menu showing you pick a different (or same) item and there is no history of previous selections persisted (like it would be in case of "radio group" model of popup menu).

Does this clarify the behavior?

Thanks,
Vlad

**Comment by SpencerLynn** [comment]
@vladfilyakov That does make sense and is what I'm getting at, ultimately. I think it's minor, but would still prefer it not show the checkmark at all in my particular use case :) 

For example, UI Fabric for Android doesn't seem to do this (as far as I remember).

**Comment by vladfilyakov** [comment]
@SpencerLynn The thing is that right now popup menu has no idea if it's used as a selector of one option or as a list of commands. So in order to differentiate these 2 use-cases we will need to add a new API. Not sure it's worth it :-) What do you think?

Zero lines of code is shared between iOS and Android versions of Fabric :-) Android's BottomSheet does not support selection at all and PopupMenu supports single and multi selection  via dedicated API. So API's are slightly different between iOS and Android.

**Comment by SpencerLynn** [comment]
@vladfilyakov I agree. It would take a new API, and would complicate the API quite a bit. I even looked into an initial implementation myself and the API does get a little weird - having to declare whether the item is an "action" or whether it's holding "selection", which is further complicated by the fact that doing that on an item-by-item basis doesn't really make sense. That more fits on the section (or even the entire popup?).

I was only mentioning Android in case there was a goal of visual/experience consistency, since there was a slight difference between them.

This issue was only a way of asking how the maintainers felt about potentially updating it to not force the checkmark on consumers.

I will come back to this when I get back to working on where I was consuming this. Until then, feel free to close this :)

**Comment by vladfilyakov** [comment]
@SpencerLynn I was thinking it would be a popup menu level API (`Bool` property, for example). Making it item or section level API would create extra complexity for a user if developers start abusing it :-)

We don't expect the same people to use both iOS and Android, so visual consistency between platforms is not that important. We want to align on functionality between platforms and make each Fabric (iOS or Android) feel at home on host OS.

I will close this until we get more feedback - and thank you Spencer for providing yours!
