### ISSUE TITLE
Swift Packages

### ISSUE THREAD

**Issue by amberreyn** [OfficeDev/ui-fabric-ios#17]
I was wondering if you plan to make this work with Swift packages.

**Comment by markavitale** [comment]
Hey amberreyn,

Swift Package Manger support is a long term goal for this repository. Unfortunately right now Swift Package Manager does not include support for resources along with code. As ui-fabric-ios requires certain resources to be bundled with the code for consumption, it is my understanding we can't currently support SPM.

According to [this Swift Package Manager proposal discussion](https://forums.swift.org/t/se-0271-package-manager-resources/30730/72), it would seem that resource support will come with Swift 5.3. After that is released we hope to investigate supporting Swift Package Manager alongside our existing package management support.

Thanks,
Mark
