### ISSUE TITLE
[Question] Are you guys open to adding screenshots of the elements in the demo to the readme page?

### ISSUE THREAD

**Issue by getaclue** [OfficeDev/ui-fabric-ios#5]
Hello team,

First and foremost ... thanks for releasing this! One of the first ui libraries that I am actually excited to try out and use on iOS. Definitely bookmarked. I've downloaded and tried the demo. I think this project may receive more traction if people saw the various elements available. I have no issue of doing the work if it aligns with what you guys want out of this project. I will simply take screenshots in the app and create a new markdown page or add to the main readme. I am open to the actual look and feel.

Please let me know if you'd like this PR or you have a team working on this already and it is not needed!

Thank you for all of the hard work! I look forward to future updates of this.

Cheers,
Alex

**Comment by vladfilyakov** [comment]
Hi Alex

Thank you for kind words - many people worked to make this project happen! We are working on updating our documentation on https://developer.microsoft.com/en-us/fabric#/controls/ios and pieces from it will trickle down to this repo as additional docs/screenshots. I appreciate your offer for help and will keep you in mind!

Thanks,
Vlad
